//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicantManagementApp.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicantManagementSystemEntities : DbContext
    {
        public ApplicantManagementSystemEntities()
            : base("name=ApplicantManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnrolledUsers> EnrolledUsers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Statements> Statements { get; set; }
        public virtual DbSet<StatementsExams> StatementsExams { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
