//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicantManagementApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementsExams
    {
        public int idStatementExam { get; set; }
        public int idSpeciality { get; set; }
        public int idUser { get; set; }
    
        public virtual Speciality Speciality { get; set; }
        public virtual Users Users { get; set; }
    }
}
